1,2c1
< terminate called after throwing an instance of 'std::invalid_argument'
<   what():  stoi
---
> ERROR: Undefined escape sequence xqq
